GuitarVendor/Models/Store.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace GuitarVendor.Models
{
  public class Store
  {
    public int StoreId { get; set; }

    [Required(ErrorMessage = "The store's name can't be empty!")]
    public string Name {get; set; }

    [Required(ErrorMessage = "The store's description can't be empty!")]
    public string Description { get; set; }
    public List<Guitar> Guitars { get; set; }
    public List<StoreGuitar> JoinEntities { get; }

  }
}

GuitarVendor/Controllers/GuitarsController.cs
using Microsoft.AspNetCore.Mvc;
using GuitarVendor.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http.Features;

namespace GuitarVendor.Controllers
{
  public class GuitarsController : Controller
  {
    private readonly GuitarVendorContext _db;
    public GuitarsController(GuitarVendorContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Guitar> model = _db.Guitars.Include(guitar => guitar.Store).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StoreId = new SelectList(_db.Stores, "StoreId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Guitar guitar)
    {
      if (!ModelState.IsValid)
      {
        ViewBag.StoreId = new SelectList(_db.Stores, "StoreId", "Name");
        return View(guitar);
      }
      else
      {
        _db.Guitars.Add(guitar);
        _db.SaveChanges();
        _db.StoreGuitars.Add(new StoreGuitar() { StoreId = guitar.StoreId, GuitarId = guitar.GuitarId });
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Guitar thisGuitar = _db.Guitars
      .Include(guitar => guitar.JoinEntities)
      .ThenInclude(guitar => guitar.Store)
      .FirstOrDefault(guitar => guitar.GuitarId == id);
      return View(thisGuitar);
    }

    public ActionResult AddStore(int id)
    {
      Guitar thisGuitar = _db.Guitars.FirstOrDefault(guitars => guitars.GuitarId == id);
      ViewBag.StoreId = new SelectList(_db.Stores, "StoreId", "Name");
      return View(thisGuitar);
    }

    [HttpPost]
    public ActionResult AddStore(Guitar guitar, int storeId)
    {
      #nullable enable
      StoreGuitar? joinEntity = _db.StoreGuitars.FirstOrDefault(join => (join.StoreGuitarId == storeId && join.GuitarId == guitar.GuitarId));
      #nullable disable
      if (joinEntity == null && storeId != 0)
      {
        _db.StoreGuitars.Add(new StoreGuitar() { StoreId = storeId, GuitarId = guitar.GuitarId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = guitar.GuitarId });
    }

    public ActionResult Edit(int id)
    {
      Guitar thisGuitar = _db.Guitars.FirstOrDefault(guitar => guitar.GuitarId == id);
      return View(thisGuitar);
    }

    [HttpPost]
    public ActionResult Edit(Guitar guitar)
    {
      _db.Guitars.Update(guitar);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Guitar thisGuitar = _db.Guitars.FirstOrDefault(guitar => guitar.GuitarId == id);
      return View(thisGuitar);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Guitar thisGuitar = _db.Guitars.FirstOrDefault(guitar => guitar.GuitarId == id);
      _db.Guitars.Remove(thisGuitar);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      StoreGuitar joinEntry = _db.StoreGuitars.FirstOrDefault(entry => entry.StoreGuitarId == joinId);
      _db.StoreGuitars.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

GuitarVendor/Controllers/StoresController.cs
using Microsoft.AspNetCore.Mvc;
using GuitarVendor.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace GuitarVendor.Controllers
{
  public class StoresController : Controller
  {
    private readonly GuitarVendorContext _db;
    public StoresController(GuitarVendorContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Store> model = _db.Stores.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Store store)
    {
      if (!ModelState.IsValid)
      {
        return View(store);
      }
      _db.Stores.Add(store);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Store thisStore = _db.Stores
      .Include(guitar => guitar.JoinEntities)
      .ThenInclude(store => store.Guitar)
      .FirstOrDefault(store => store.StoreId == id);
      return View(thisStore);
    }

    public ActionResult Edit(int id)
    {
      Store thisStore = _db.Stores.FirstOrDefault(store => store.StoreId == id);
      return View(thisStore);
    }

    [HttpPost]
    public ActionResult Edit(Store store)
    {
      _db.Stores.Update(store);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Store thisStore = _db.Stores.FirstOrDefault(store => store.StoreId == id);
      return View(thisStore);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Store thisStore = _db.Stores.FirstOrDefault(stores => stores.StoreId == id);
      _db.Stores.Remove(thisStore);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      StoreGuitar joinEntry = _db.StoreGuitars.FirstOrDefault(entry => entry.StoreGuitarId == joinId);
      _db.StoreGuitars.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddGuitar(int id)
    {
      Store thisStore = _db.Stores.FirstOrDefault(stores => stores.StoreId == id);
      ViewBag.GuitarId = new SelectList(_db.Guitars, "GuitarId", "Year", "Brand", "Model");
      return View(thisStore);
    }

    [HttpPost]
    public ActionResult AddGuitar(Store store, int guitarId)
    {
      #nullable enable
      StoreGuitar? joinEntity = _db.StoreGuitars.FirstOrDefault(join => join.StoreGuitarId == guitarId && join.StoreId == store.StoreId );
      #nullable disable
      if (joinEntity == null && guitarId != 0)
      {
        _db.StoreGuitars.Add(new StoreGuitar() { GuitarId = guitarId, StoreId = store.StoreId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = store.StoreId });
    }

  }
}

GuitarVendor/Views/Stores/AddGuitar.cshtml
@{
  Layout = "_Layout";
}

@model GuitarVendor.Models.Store
@using GuitarVendor.Models

<h2>Add a guitar</h2>

<h4>Add a guitar to this store: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StoreId)
  @Html.Label("Select guitar")
  @Html.DropDownList("GuitarId")
  <input type="submit" class="btn btn-primary" value="Add"/>
}
<br>
<p>@Html.ActionLink("Back to store list", "Index")</p>

GuitarVendor/Views/Stores/Create.cshtml
@{
  Layout = "_Layout";
}

@model GuitarVendor.Models.Store
@using GuitarVendor.Models

<h4>Add a new store</h4>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class="text-danger", @style = "font-weight: 600;" })</p>
<p>@Html.ValidationMessageFor(model => model.Description, "", new {@class="text-danger", @style = "font-weight: 600;" })</p>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  <br>
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  <br>
  <br>
  <input type="submit" value="Add new store" class="btn btn-primary"/>
}
<br>
<p>@Html.ActionLink("View all stores", "Index")</p>

GuitarVendor/Views/Stores/Delete.cshtml
@{
  Layout = "_Layout";
}

@model GuitarVendor.Models.Store

<h2>Are you sure you want to delete this store?</h2>

<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>
<h4>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h4>
@using (Html.BeginForm())
{
  <input type="submit" class="btn btn-primary" value="Delete"/>
}
<br>
<p>@Html.ActionLink("Back to store list", "Index")</p>

GuitarVendor/Views/Stores/Details.cshtml
@{
  Layout = "_Layout";
}

@model GuitarVendor.Models.Store
@using GuitarVendor.Models
@using System.Collections.Generic;

<h2>Store Details</h2>
<hr>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <h3>No guitars have been added to this store yet.</h3>
}
else
{
  <h3>Guitars in stock at this store:</h3>
  <ul>
    @foreach (StoreGuitar join in Model.JoinEntities)
    {
      <li>@join.Guitar.Year @join.Guitar.Brand @join.Guitar.Model</li>
      @using (Html.BeginForm("DeleteJoin", "Stores"))
      {
        @Html.Hidden("joinId", @join.StoreGuitarId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
}

<p>@Html.ActionLink("Add a guitar to this store", "AddGuitar", new { id = Model.StoreId })</p>
<p>@Html.ActionLink("Edit this store", "Edit", new { id = Model.StoreId })</p>
<p>@Html.ActionLink("Delete this store", "Delete", new { id = Model.StoreId })</p>
<p>@Html.ActionLink("View guitar list", "Index", "Guitars")</p>
<p>@Html.ActionLink("View store list", "Index")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

GuitarVendor/Views/Stores/Edit.cshtml
@{
  Layout = "_Layout";
}

@model GuitarVendor.Models.Store

<h2>Edit</h2>

<h4>Edit this store: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StoreId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  <br>
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)
  <br>
  <br>
  <input type="submit" class="btn btn-primary" value="Edit"/>
}
<br>
<p>@Html.ActionLink("Back to store list", "Index")</p>

GuitarVendor/Views/Stores/Index.cshtml
@{
  Layout = "_Layout";
}

@using GuitarVendor.Models;

<h1>Stores</h1>

@if (@Model.Count == 0)
{
  <h3>No stores have been added yet.</h3>
}

<ul>
  @foreach (Store store in Model)
  {
    <li>@Html.ActionLink($"{store.Name}", "Details", new { id = store.StoreId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new store", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>